/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Block: typeof import('./../src/components/editor/src/block.vue')['default']
    Config: typeof import('./../src/components/editor/src/config.vue')['default']
    Editor: typeof import('./../src/components/editor/index.ts')['default']
    EditorBlock: typeof import('./../src/components/editor/src/editor-block.vue')['default']
    EditorConfig: typeof import('./../src/components/editor/src/editor-config.vue')['default']
    EditorHeader: typeof import('./../src/components/editor/src/editor-header.vue')['default']
    EditorRender: typeof import('./../src/components/editor/src/editor-render.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./../src/components/editor/src/header.vue')['default']
    Icon: typeof import('@iconify/vue')['Icon']
    Render: typeof import('./../src/components/editor/src/render.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VIcon: typeof import('./../src/components/common/v-icon.vue')['default']
    VIconTooltip: typeof import('./../src/components/common/v-icon-tooltip.vue')['default']
    VSelect: typeof import('./../src/components/common/v-select.vue')['default']
  }
}
